-- [VIII] Sequence : 순차번호 생성기. 인위적인 PK 사용 용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
	START WITH 1 -- 1부터 시작(기본값)
	INCREMENT BY 1 -- 1씩 증가(기본값)
	MAXVALUE 9999 -- 최대값
	MINVALUE 1    -- 최소값
	NOCACHE
	NOCYCLE;
	
SELECT FRIEND_SEQ.NEXTVAL FROM DUAL; -- 다음 순차번호 생성
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; -- 시퀀스의 현재 값

-- EX1. FRIEND테이블(NO-PK, NAME, TEL, ADDRESS, LAST_MODIFY)
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
	MAXVALUE 99999
	NOCACHE
	NOCYCLE;
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
	NO 			NUMBER(5),
	NAME 		VARCHAR2(30) 	NOT NULL,
	TEL 		VARCHAR2(20) 	UNIQUE, -- NULL허용. NULL이 아닐 때는 유일한 값
	ADDRESS 	VARCHAR2(255),
	LAST_MODIFY DATE 			DEFAULT SYSDATE,
	PRIMARY KEY(NO)
);

INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', NULL, '서울시 관악구'); -- 몇번 실행 가능

SELECT * FROM FRIEND;

INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
VALUES(FRIEND_SEQ.NEXTVAL, NULL, '010-9999-9999','서울'); -- 에러 (NOT NULL)

INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
VALUES(FRIEND_SEQ.NEXTVAL, '박길동', '010-9999-9999','서울');

SELECT * FROM FRIEND;

-- EX2. FRIEND테이블(NO 20240924001 날짜002, NAME, TEL, ADDRESS, LAST_MODIFY)
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
	MAXVALUE 999
	NOCACHE
	NOCYCLE;
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
	NO 			NUMBER(11),
	NAME 		VARCHAR2(30) 	NOT NULL,
	TEL 		VARCHAR2(20) 	UNIQUE, -- NULL허용. NULL이 아닐 때는 유일한 값
	ADDRESS 	VARCHAR2(255),
	LAST_MODIFY DATE 			DEFAULT SYSDATE,
	PRIMARY KEY(NO)
);

SELECT TO_CHAR(SYSDATE,'YYYYMMDD') || TRIM(TO_CHAR(1,'000')) FROM DUAL;

INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
VALUES (TO_CHAR(SYSDATE,'YYYYMMDD') || TRIM(TO_CHAR(FRIEND_SEQ.NEXTVAL,'000')), '홍길동', NULL, '서울시 관악구'); -- 몇번 실행 가능

SELECT * FROM FRIEND;

INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
VALUES(FRIEND_SEQ.NEXTVAL, NULL, '010-9999-9999','서울'); -- 에러 (NOT NULL)

INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
VALUES(FRIEND_SEQ.NEXTVAL, '박길동', '010-9999-9999','서울');

SELECT * FROM FRIEND;

-- QUIZ
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;

CREATE TABLE MEMBER_LEVEL(
	LEVELNO 	NUMBER(2),
	LEVELNAME 	VARCHAR2(50) NOT NULL,
	PRIMARY KEY (LEVELNO)
);

CREATE TABLE MEMBER(
	mNO 	NUMBER(10),
	mNAME 	VARCHAR2(30) 	NOT NULL,
	mPW 	VARCHAR2(8) 	NOT NULL,
	mEMAIL 	VARCHAR2(100) 	UNIQUE,
	mPOINT 	NUMBER(10) 		CHECK (0<=mPOINT),
	mRDATE 	DATE 			DEFAULT SYSDATE,
	LEVELNO NUMBER(2),
	PRIMARY KEY(mNO),
	FOREIGN KEY(LEVELNO) REFERENCES MEMBER_LEVEL(LEVELNO)
);

DROP SEQUENCE MEMBER_MNO_SQ;
CREATE SEQUENCE MEMBER_MNO_SQ
	MAXVALUE 999
	NOCACHE
	NOCYCLE;

INSERT INTO MEMBER_LEVEL(LEVELNO, LEVELNAME)
VALUES (-1, 'black');
INSERT INTO MEMBER_LEVEL(LEVELNO, LEVELNAME)
VALUES (0, '일반');
INSERT INTO MEMBER_LEVEL(LEVELNO, LEVELNAME)
VALUES (1, '실버');
INSERT INTO MEMBER_LEVEL(LEVELNO, LEVELNAME)
VALUES (2, '골드');

SELECT * FROM MEMBER_LEVEL;

INSERT INTO MEMBER(mNO, mNAME, mPW, mEMAIL, mPOINT, mRDATE, LEVELNO)
VALUES(MEMBER_MNO_SQ.NEXTVAL, '홍길동', 'aa', 'hong@hong.com', 0, '22/03/10', 0);
INSERT INTO MEMBER(mNO, mNAME, mPW, mEMAIL, mPOINT, mRDATE, LEVELNO)
VALUES(MEMBER_MNO_SQ.NEXTVAL, '신길동', 'bb', 'sin@sin.com', 1000, '22/04/01', 1);

SELECT * FROM MEMBER;

SELECT mNO, mNAME, TO_CHAR(mRDATE,'YYYY-MM-DD') "mRDATE", mEMAIL "mMAIL", mPOINT "point", LEVELNAME || TRIM('고객') "levelname"
FROM MEMBER M, MEMBER_LEVEL L
WHERE M.LEVELNO=L.LEVELNO;