DROP TABLE ORDER_DETAIL;
DROP TABLE ORDERS;
DROP TABLE CART;
DROP TABLE PRODUCT;
DROP TABLE MEMBER;

CREATE TABLE MEMBER(
	mID 	 VARCHAR2(30),
	mNAME 	 VARCHAR2(10) NOT NULL,
	mADDRESS VARCHAR2(30) NOT NULL,
	mTEL 	 VARCHAR2(13) NOT NULL UNIQUE,
	mEMAIL 	 VARCHAR2(30) NOT NULL,
	PRIMARY KEY (mID)
);

CREATE TABLE PRODUCT(
	pCODE VARCHAR2(3),
	pNAME VARCHAR2(10) 	NOT NULL,
	PRICE NUMBER(5) 	NOT NULL CHECK(PRICE>=0),
	STOCK NUMBER(4) 	NOT NULL CHECK(STOCK>=0),
	PRIMARY KEY(pCODE)
);

CREATE TABLE CART(
	cNO 	VARCHAR2(3),
	mID 	VARCHAR2(30),
	pCODE 	VARCHAR2(3),
	QTY 	NUMBER(3)	 NOT NULL CHECK(QTY>0),
	cost 	NUMBER(5)	 NOT NULL CHECK(cost>=0),
	PRIMARY KEY(cNO),
	FOREIGN KEY(mID) 	REFERENCES MEMBER(mID),
	FOREIGN KEY(pCODE) 	REFERENCES PRODUCT(pCODE)
);

CREATE TABLE ORDERS(
	oNO 	VARCHAR2(9),
	mID 	VARCHAR2(30),
	oNAME 	VARCHAR2(10),
	oADDR 	VARCHAR2(30),
	oTEL 	VARCHAR2(13),
	oDATE 	DATE 			DEFAULT SYSDATE,
	PRIMARY KEY(oNO),
	FOREIGN KEY(mID) REFERENCES MEMBER(mID)
);

CREATE TABLE ORDER_DETAIL(
	odNO 	NUMBER(2),
	oNO 	VARCHAR2(9),
	pCODE 	VARCHAR2(3),
	QTY 	NUMBER(3) 	NOT NULL CHECK(QTY>0),
	cost 	NUMBER(5) 	NOT NULL CHECK(cost>=0),
	PRIMARY KEY(odNO),
	FOREIGN KEY(oNO) REFERENCES ORDERS(oNO),
	FOREIGN KEY(pCODE) REFERENCES PRODUCT(pCODE)
);

INSERT INTO MEMBER(mID, mNAME, mADDRESS, mTEL, mEMAIL)
VALUES ('abc', '홍길동', '서울시 관악구 신림동', '010-9999-9999', 'hong@hong.com');

INSERT INTO MEMBER(mID, mNAME, mADDRESS, mTEL, mEMAIL)
VALUES ('def', '김김동', '경기도 수원시', '010-8888-8888', 'kim@kim.com');

SELECT * FROM MEMBER;

INSERT INTO PRODUCT(pCODE, pNAME, PRICE, STOCK)
VALUES ('A1', '맥주', 3000, 5);

INSERT INTO PRODUCT(pCODE, pNAME, PRICE, STOCK)
VALUES ('A2', '마스크', 200, 20);

INSERT INTO PRODUCT(pCODE, pNAME, PRICE, STOCK)
VALUES ('B1', '땅콩', 3000, 2);

INSERT INTO PRODUCT(pCODE, pNAME, PRICE, STOCK)
VALUES ('B2', '오징어', 5000, 2);

INSERT INTO PRODUCT(pCODE, pNAME, PRICE, STOCK)
VALUES ('C1', '소독약', 7000, 1);

SELECT * FROM PRODUCT;

DROP SEQUENCE cNO_SEQ;
CREATE SEQUENCE cNO_SEQ
	MAXVALUE 9999
	NOCACHE
	NOCYCLE;
INSERT INTO CART(cNO, mID, pCODE, QTY, cost)
VALUES(cNO_SEQ.NEXTVAL, 'abc', 'A1', 3, 3*(
		SELECT PRICE
		FROM PRODUCT
		WHERE pCODE='A1'
		)
	);
INSERT INTO CART(cNO, mID, pCODE, QTY, cost)
VALUES(cNO_SEQ.NEXTVAL, 'abc', 'B1', 1, 1*(
		SELECT PRICE
		FROM PRODUCT
		WHERE pCODE='B1'
		)
	);
INSERT INTO CART(cNO, mID, pCODE, QTY, cost)
VALUES(cNO_SEQ.NEXTVAL, 'def', 'A2', 20, 20*(
		SELECT PRICE
		FROM PRODUCT
		WHERE pCODE='A2'
		)
	);
INSERT INTO CART(cNO, mID, pCODE, QTY, cost)
VALUES(cNO_SEQ.NEXTVAL, 'def', 'A1', 2, 2*(
		SELECT PRICE
		FROM PRODUCT
		WHERE pCODE='A1'
		)
	);

SELECT * FROM CART;

DROP SEQUENCE ORD_SEQ;
CREATE SEQUENCE ORD_SEQ
	NOCACHE
	NOCYCLE;
INSERT INTO ORDERS(oNO, mID, oNAME, oADDR, oTEL, oDATE)
VALUES(
	TO_CHAR(SYSDATE,'RRMMDD')||TRIM(TO_CHAR(ORD_SEQ.NEXTVAL,'000')),
	'abc',
	(
		SELECT mNAME
		FROM MEMBER
		WHERE mID='abc'
	),
	(
		SELECT mADDRESS
		FROM MEMBER
		WHERE mID='abc'
	),
	(
		SELECT mTEL
		FROM MEMBER
		WHERE mID='abc'
	),
	SYSDATE
);
SELECT * FROM ORDERS;

DROP SEQUENCE odNO_SEQ;
CREATE SEQUENCE odNO_SEQ
	NOCACHE
	NOCYCLE;
INSERT INTO ORDER_DETAIL(odNO, oNO, pCODE, QTY, cost)
SELECT 	odNO_SEQ.NEXTVAL odNO,
		TO_CHAR(SYSDATE,'RRMMDD')||TRIM(TO_CHAR(ORD_SEQ.CURRVAL,'000')) oNO,
		pCODE, QTY, COST
FROM CART
WHERE mID='abc';

SELECT * FROM ORDER_DETAIL;