--1
SELECT EMPNO, ENAME
FROM EMP
WHERE ENAME LIKE '%A%';

--2
SELECT ENAME, JOB, DNAME, LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO 
    AND ENAME LIKE '%L%';

--3
SELECT EMPNO, ENAME, JOB, SAL, GRADE
FROM EMP, SALGRADE
WHERE SAL BETWEEN LOSAL AND HISAL
ORDER BY SAL DESC;

--4
SELECT E.ENAME, E.SAL, E.DEPTNO, LOC, NVL(M.ENAME,'없음') "MNAME"
FROM EMP E, EMP M, DEPT D
WHERE E.MGR=M.EMPNO(+)
    AND E.DEPTNO=D.DEPTNO;

--5
SELECT EMPNO, ENAME, JOB, TO_CHAR(SAL, '$999,999') SAL
FROM EMP
WHERE DEPTNO=20;

--6
SELECT ENAME, JOB
FROM EMP
WHERE MGR=(
        SELECT EMPNO
        FROM EMP
        WHERE ENAME='KING'
    );

--7
UPDATE EMP
SET SAL = SAL*1.1
WHERE SAL>=3000;

--8
DELETE FROM EMP
WHERE ENAME = 'FORD';

--9
DROP TABLE STUDENT;
DROP TABLE MAJOR;

CREATE TABLE MAJOR(
    mCODE   NUMBER(2),
    mNAME   VARCHAR2(30) UNIQUE,
    mOFFICE VARCHAR2(50),
    PRIMARY KEY(mCODE)
);

CREATE TABLE STUDENT(
    sNO     VARCHAR2(3),
    sNAME   VARCHAR2(50),
    sSCORE  NUMBER(3) CHECK (sSCORE BETWEEN 1 AND 100),
    mCODE   NUMBER(2),
    PRIMARY KEY(sNO),
    FOREIGN KEY(mCODE) REFERENCES MAJOR(mCODE)
);

INSERT INTO MAJOR(mCODE, mNAME, mOFFICE)
VALUES (1, '컴퓨터공학', 'A101호');

INSERT INTO MAJOR(mCODE, mNAME, mOFFICE)
VALUES (2, '빅데이터', 'A102호');

SELECT * FROM MAJOR;

INSERT INTO STUDENT(sNO, sNAME, sSCORE, mCODE)
VALUES ('101', '홍길동', 99, 1);

INSERT INTO STUDENT(sNO, sNAME, sSCORE, mCODE)
VALUES ('102', '신길동', 100, 2);

SELECT * FROM STUDENT;

SELECT sNO, sNAME, sSCORE, S.mCODE, mNAME, mOFFICE
FROM MAJOR M, STUDENT S
WHERE M.mCODE=S.mCODE;

-- 10
SELECT DNAME, COUNT(*)
FROM EMP E, DEPT D
WHERE E.DEPTNO = D. DEPTNO
GROUP BY DNAME
HAVING COUNT(*)>=5;