DROP TABLE PERSON;
DROP TABLE JOB;

CREATE TABLE JOB(
	jNO NUMBER(2),
	jNAME VARCHAR2(30) NOT NULL,
	PRIMARY KEY(jNO)
);

CREATE TABLE PERSON(
	pNO NUMBER(5),
	pNAME VARCHAR2(30) NOT NULL,
	jNO NUMBER(2),
	KOR NUMBER(3),
	ENG NUMBER(3),
	MAT NUMBER(3),
	PRIMARY KEY(pNO),
	FOREIGN KEY(jNO) REFERENCES JOB(jNO)
);

INSERT INTO JOB(jNO, jNAME)
VALUES(10, '배우');
INSERT INTO JOB(jNO, jNAME)
VALUES(20, '가수');
INSERT INTO JOB(jNO, jNAME)
VALUES(30, '엠씨');

DROP SEQUENCE p_SEQ;
CREATE SEQUENCE p_SEQ
	MAXVALUE 999
	NOCACHE
	NOCYCLE;
-- 직업리스트
SELECT * FROM JOB;
--1 이름, 직업명, 국어, 영어, 수학점수 입력 데이터 베이스에 번호를 포함하여 입력한다.
INSERT INTO PERSON(pNO, pNAME, jNO, KOR, ENG, MAT)
VALUES(p_SEQ.NEXTVAL, '정우성',(
		SELECT JNO
		FROM JOB
		WHERE JNAME='배우'
	), 90, 80, 81);
INSERT INTO PERSON(pNO, pNAME, jNO, KOR, ENG, MAT)
VALUES(p_SEQ.NEXTVAL, '박세영', (
		SELECT JNO
		FROM JOB
		WHERE JNAME='배우'
	), 80, 90, 80);
INSERT INTO PERSON(pNO, pNAME, jNO, KOR, ENG, MAT)
VALUES(p_SEQ.NEXTVAL, '배수지', (
		SELECT JNO
		FROM JOB
		WHERE JNAME='가수'
	), 20, 90, 90);
--2 직업명 입력, 직업별 조회 후 총점추가 총점이 높은 순으로 이름(번호) 출력
SELECT ROWNUM||'등' "RANK", A.* 
FROM (
	SELECT pNAME||'('||pNO||'번)' "pNAME", jNAME, KOR, ENG, MAT, (KOR+ENG+MAT) "TOT"
	FROM PERSON P, JOB J
	WHERE P.jNO=J.jNO
		AND jNAME='배우'
	ORDER BY TOT DESC
) A;

--3 전체 사람 조회 후 총점 추가 높은순 출력
SELECT ROWNUM||'등' "RANK", A.* 
FROM (
	SELECT pNAME||'('||pNO||'번)' "pNAME", jNAME, KOR, ENG, MAT, (KOR+ENG+MAT) "TOT"
	FROM PERSON P, JOB J
	WHERE P.jNO=J.jNO
	ORDER BY TOT DESC
) A;